/// Lista clasificada de textura de suelo basada en USDA (United States Department of Agriculture).
const List<String> kUSDA_SoilTypes = [
  'Arena',
  'Arena franca',
  'Franco arenoso',
  'Franco',
  'Franco limoso',
  'Limo',
  'Franco arcillo arenoso',
  'Franco arcilloso',
  'Franco arcillo limoso',
  'Arcilla arenosa',
  'Arcilla limosa',
  'Arcilla',
];

/// Lista extensiva de cultivos (+100 tipos comunes) en orden alfabético.
const List<String> kComprehensiveCropTypes = [
  'Acelga',
  'Achira',
  'Agave',
  'Aguacate',
  'Ahipa',
  'Ajo',
  'Ajonjolí',
  'Albahaca',
  'Alcachofa',
  'Alfalfa',
  'Algodón',
  'Almendra',
  'Aloe Vera',
  'Amaranto',
  'Apio',
  'Arándano',
  'Árbol de pan',
  'Arracacha',
  'Arroz',
  'Arveja',
  'Avena',
  'Azafrán',
  'Badea',
  'Banano',
  'Berenjena',
  'Berro',
  'Boniato',
  'Brócoli',
  'Caballo',
  'Cacao',
  'Café',
  'Calabacín',
  'Calabaza',
  'Camote',
  'Canela',
  'Caña de azúcar',
  'Cardamomo',
  'Cártamo',
  'Castaña',
  'Cebada',
  'Cebolla',
  'Centeno',
  'Cereza',
  'Champiñón',
  'Chayote',
  'Chícharo',
  'Chile',
  'Chirimoya',
  'Cilantro',
  'Ciruela',
  'Coco',
  'Coliflor',
  'Comino',
  'Cúrcuma',
  'Curuba',
  'Durazno',
  'Espárrago',
  'Espinaca',
  'Frambuesa',
  'Fresa',
  'Frijol',
  'Garbanzo',
  'Girasol',
  'Granada',
  'Granadilla',
  'Guanábana',
  'Guayaba',
  'Haba',
  'Higo',
  'Jengibre',
  'Jitomate',
  'Kiwi',
  'Lechuga',
  'Lenteja',
  'Lima',
  'Limón',
  'Lino',
  'Lulo',
  'Macadamia',
  'Mandarina',
  'Maní',
  'Mango',
  'Manzana',
  'Maracuyá',
  'Marañón',
  'Maíz',
  'Melocotón',
  'Melón',
  'Menta',
  'Mora',
  'Mostaza',
  'Naranja',
  'Níspero',
  'Nuez',
  'Oliva',
  'Orégano',
  'Palma de aceite',
  'Papa',
  'Papaya',
  'Pecana',
  'Pepino',
  'Pera',
  'Pimentón',
  'Pimienta',
  'Piña',
  'Plátano',
  'Pomelo',
  'Puerro',
  'Quinua',
  'Rábano',
  'Remolacha',
  'Repollo',
  'Romero',
  'Sandía',
  'Sésamo',
  'Soya',
  'Tabaco',
  'Tamarindo',
  'Tomate',
  'Tomate de árbol',
  'Toronja',
  'Trigo',
  'Uchuva',
  'Uva',
  'Vainilla',
  'Zanahoria',
  'Zarzamora',
];
